import type { CompletionCommand, CompletionInfo } from "./types.js";
import { sanitizeShellToken } from "./types.js";

const MAX_COMPLETION_DEPTH = 20;

function generateCommandCase(
	brand: string,
	cmd: CompletionCommand,
	path: string,
	depth = 0,
): string {
	if (depth > MAX_COMPLETION_DEPTH) return "";

	const lines: string[] = [];
	const safeName = sanitizeShellToken(cmd.name);
	const casePattern = path ? `${path}_${safeName}` : safeName;

	// Gather completions for this command
	const words: string[] = [];

	// Add subcommands
	if (cmd.subcommands) {
		for (const sub of cmd.subcommands) {
			words.push(sanitizeShellToken(sub.name));
		}
	}

	// Add flags
	if (cmd.flags) {
		for (const f of cmd.flags) {
			words.push(`--${sanitizeShellToken(f.name)}`);
			if (f.alias) words.push(`-${sanitizeShellToken(f.alias)}`);
		}
	}

	if (words.length > 0) {
		lines.push(`        ${casePattern})`);
		lines.push(`            COMPREPLY=( $(compgen -W "${words.join(" ")}" -- "\${cur}") )`);
		lines.push("            return 0");
		lines.push("            ;;");
	}

	// Recurse for subcommands
	if (cmd.subcommands) {
		for (const sub of cmd.subcommands) {
			lines.push(generateCommandCase(brand, sub, casePattern, depth + 1));
		}
	}

	return lines.join("\n");
}

/**
 * Generate a bash completion script.
 *
 * Uses a lookup key built from all command tokens (words[1]..words[cword-1])
 * joined with underscores so that nested subcommand completions are reachable.
 * For example, `mycli db migrate <TAB>` builds the key "db_migrate" which
 * matches the case pattern generated by generateCommandCase.
 */
export function bash(info: CompletionInfo): string {
	const { brand, commands } = info;
	const safeBrand = sanitizeShellToken(brand);

	const topLevelWords = commands
		.flatMap((c) => [sanitizeShellToken(c.name), ...(c.aliases ?? []).map(sanitizeShellToken)])
		.join(" ");

	const caseClauses: string[] = [];
	for (const cmd of commands) {
		caseClauses.push(generateCommandCase(safeBrand, cmd, ""));
	}

	return `# Bash completions for ${safeBrand}
# Generated by @seedcli/completions

_${safeBrand}_completions() {
    local cur prev words cword
    _init_completion || return

    if [[ \${cword} -eq 1 ]]; then
        COMPREPLY=( $(compgen -W "${topLevelWords}" -- "\${cur}") )
        return 0
    fi

    # Build a lookup key from all command tokens before the cursor.
    # e.g. "mycli db migrate <TAB>" → key="db_migrate"
    local key=""
    for ((i=1; i < cword; i++)); do
        if [[ "\${words[i]}" == -* ]]; then
            continue
        fi
        if [[ -n "$key" ]]; then
            key="\${key}_\${words[i]}"
        else
            key="\${words[i]}"
        fi
    done

    case "$key" in
${caseClauses.join("\n")}
        *)
            ;;
    esac
}

complete -F _${safeBrand}_completions ${safeBrand}
`;
}
