import type { CompletionCommand, CompletionInfo } from "./types.js";
import { escapeShellDescription, sanitizeShellToken } from "./types.js";

const MAX_COMPLETION_DEPTH = 20;

function generateFishCompletions(
	brand: string,
	cmd: CompletionCommand,
	condition: string,
	depth = 0,
): string[] {
	if (depth > MAX_COMPLETION_DEPTH) return [];

	const lines: string[] = [];
	const safeName = sanitizeShellToken(cmd.name);
	const desc = cmd.description ? ` -d '${escapeShellDescription(cmd.description)}'` : "";

	// Add the command itself as a completion
	lines.push(`complete -c ${brand} ${condition} -a '${safeName}'${desc}`);

	// Add aliases
	if (cmd.aliases) {
		for (const alias of cmd.aliases) {
			lines.push(`complete -c ${brand} ${condition} -a '${sanitizeShellToken(alias)}'${desc}`);
		}
	}

	// Subcommand condition: we need the parent command in the args
	const subCondition = `-n '__fish_seen_subcommand_from ${safeName}'`;

	// Add flags for this command
	if (cmd.flags) {
		for (const f of cmd.flags) {
			const safeFlagName = sanitizeShellToken(f.name);
			const flagDesc = f.description ? ` -d '${escapeShellDescription(f.description)}'` : "";
			let line = `complete -c ${brand} ${subCondition} -l '${safeFlagName}'`;
			if (f.alias) {
				line += ` -s '${sanitizeShellToken(f.alias)}'`;
			}
			if (f.choices && f.choices.length > 0) {
				line += ` -r -a '${f.choices.map(sanitizeShellToken).join(" ")}'`;
			}
			line += flagDesc;
			lines.push(line);
		}
	}

	// Recurse for subcommands
	if (cmd.subcommands) {
		for (const sub of cmd.subcommands) {
			lines.push(...generateFishCompletions(brand, sub, subCondition, depth + 1));
		}
	}

	return lines;
}

/**
 * Generate fish completion commands.
 */
export function fish(info: CompletionInfo): string {
	const { brand, commands } = info;
	const safeBrand = sanitizeShellToken(brand);
	const lines: string[] = [
		`# Fish completions for ${safeBrand}`,
		`# Generated by @seedcli/completions`,
		"",
	];

	const topLevelCondition = `-n 'not __fish_seen_subcommand_from ${commands.map((c) => sanitizeShellToken(c.name)).join(" ")}'`;

	for (const cmd of commands) {
		lines.push(...generateFishCompletions(safeBrand, cmd, topLevelCondition));
	}

	return `${lines.join("\n")}\n`;
}
