function generateFishCompletions(brand, cmd, condition) {
    const lines = [];
    const desc = cmd.description ? ` -d '${cmd.description.replace(/'/g, "'\\''")}'` : "";
    // Add the command itself as a completion
    lines.push(`complete -c ${brand} ${condition} -a '${cmd.name}'${desc}`);
    // Add aliases
    if (cmd.aliases) {
        for (const alias of cmd.aliases) {
            lines.push(`complete -c ${brand} ${condition} -a '${alias}'${desc}`);
        }
    }
    // Subcommand condition: we need the parent command in the args
    const subCondition = `-n '__fish_seen_subcommand_from ${cmd.name}'`;
    // Add flags for this command
    if (cmd.flags) {
        for (const f of cmd.flags) {
            const flagDesc = f.description ? ` -d '${f.description.replace(/'/g, "'\\''")}'` : "";
            let line = `complete -c ${brand} ${subCondition} -l '${f.name}'`;
            if (f.alias) {
                line += ` -s '${f.alias}'`;
            }
            if (f.choices && f.choices.length > 0) {
                line += ` -r -a '${f.choices.join(" ")}'`;
            }
            line += flagDesc;
            lines.push(line);
        }
    }
    // Recurse for subcommands
    if (cmd.subcommands) {
        for (const sub of cmd.subcommands) {
            lines.push(...generateFishCompletions(brand, sub, subCondition));
        }
    }
    return lines;
}
/**
 * Generate fish completion commands.
 */
export function fish(info) {
    const { brand, commands } = info;
    const lines = [
        `# Fish completions for ${brand}`,
        `# Generated by @seedcli/completions`,
        "",
    ];
    const topLevelCondition = `-n 'not __fish_seen_subcommand_from ${commands.map((c) => c.name).join(" ")}'`;
    for (const cmd of commands) {
        lines.push(...generateFishCompletions(brand, cmd, topLevelCondition));
    }
    return `${lines.join("\n")}\n`;
}
//# sourceMappingURL=fish.js.map