import type { CompletionCommand, CompletionInfo } from "./types.js";

function generateCommandCompletions(cmd: CompletionCommand, indent: string): string[] {
	const lines: string[] = [];

	// Add subcommands
	if (cmd.subcommands) {
		for (const sub of cmd.subcommands) {
			const desc = sub.description ? sub.description.replace(/'/g, "''") : sub.name;
			lines.push(
				`${indent}[CompletionResult]::new('${sub.name}', '${desc}', [CompletionResultType]::ParameterValue, '${desc}')`,
			);
		}
	}

	// Add flags
	if (cmd.flags) {
		for (const f of cmd.flags) {
			const desc = f.description ? f.description.replace(/'/g, "''") : `--${f.name}`;
			lines.push(
				`${indent}[CompletionResult]::new('--${f.name}', '${desc}', [CompletionResultType]::ParameterName, '${desc}')`,
			);
			if (f.alias) {
				lines.push(
					`${indent}[CompletionResult]::new('-${f.alias}', '${desc}', [CompletionResultType]::ParameterName, '${desc}')`,
				);
			}
		}
	}

	return lines;
}

/**
 * Generate a PowerShell `Register-ArgumentCompleter` script.
 */
export function powershell(info: CompletionInfo): string {
	const { brand, commands } = info;

	const commandCases: string[] = [];
	for (const cmd of commands) {
		const completions = generateCommandCompletions(cmd, "                ");
		if (completions.length > 0) {
			commandCases.push(`            '${cmd.name}' {
${completions.join("\n")}
            }`);
		}
	}

	const topLevelCompletions = commands
		.map((c) => {
			const desc = c.description ? c.description.replace(/'/g, "''") : c.name;
			return `            [CompletionResult]::new('${c.name}', '${desc}', [CompletionResultType]::ParameterValue, '${desc}')`;
		})
		.join("\n");

	return `# PowerShell completions for ${brand}
# Generated by @seedcli/completions

Register-ArgumentCompleter -CommandName '${brand}' -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)

    $tokens = $commandAst.ToString().Split(' ', [StringSplitOptions]::RemoveEmptyEntries)

    if ($tokens.Length -le 1) {
${topLevelCompletions}
        return
    }

    $command = $tokens[1]

    switch ($command) {
${commandCases.join("\n")}
    }
} | Where-Object { $_.CompletionText -like "$wordToComplete*" }
`;
}
